<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Skaliyaperumal1M-BNG1" failures="3" tests="5" name="Test" time="0.031" errors="0" timestamp="12 Nov 2022 09:31:17 GMT">
  <testcase classname="com.test.report.TestReport" name="testFail" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.qa.report.Assertion.assertEquals(Assertion.java:87)
	at com.test.report.TestReport.testFail(TestReport.java:16)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testFail -->
  <testcase classname="com.test.report.TestReport" name="testFailNumber" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at com.qa.report.Assertion.assertEquals(Assertion.java:73)
	at com.test.report.TestReport.testFailNumber(TestReport.java:21)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testFailNumber -->
  <testcase classname="com.test.report.TestReport" name="testFailString" time="0.001">
    <failure type="java.lang.AssertionError" message="Both are not equal expected [Yamuna] but found [Sakthi]">
      <![CDATA[java.lang.AssertionError: Both are not equal expected [Yamuna] but found [Sakthi]
	at com.qa.report.Assertion.assertEquals(Assertion.java:59)
	at com.test.report.TestReport.testFailString(TestReport.java:26)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testFailString -->
  <testcase classname="com.test.report.TestReport" name="testPass" time="0.001"/>
  <testcase classname="com.test.report.TestReport" name="testPassString" time="0.001"/>
</testsuite> <!-- Test -->
